from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    policy_report: Annotated[str, "Report from the Policy Analyst (A-stock specific)"]
    hot_money_report: Annotated[str, "Report from the Hot Money Tracker (A-stock specific)"]
    lockup_report: Annotated[str, "Report from the Lockup/Reduction Watcher (A-stock specific)"]

    # data quality gate
    data_quality_summary: Annotated[str, "Quality gate assessment of all analyst reports (hard checks + LLM review)"]
    # 本次实际进图的分析师键（market/social/... 的子集）。门控据此**只对已运行的分析师判级**——
    # 未选中的分析师若按空报告一律判 F，会在 7 项里凭空凑出 ≥4 个 F，反而把 LLM 复审整段跳过。
    selected_analysts: Annotated[list, "Analyst keys actually included in this run"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    # 终裁产出的形态：structured / structured-json / freetext / freetext-fallback
    # （见 utils/structured.py；`structured-json` 是 0.5.33 新增的 json_mode 通道）。
    # 自由文本不保证带 `**Rating**:` 标签——不记录来源就无法区分"模型说 Hold"与
    # "评级没解析出来、落到了默认值"。
    final_decision_format: Annotated[str, "How the final decision was produced (structured vs free text)"]
    # 评级从哪里读出来的：label（显式标签）/ bare（正文裸词）/ fallback（什么都没找到，
    # 已回落到默认 Hold）。fallback 必须与真正的 Hold 区别对待。
    rating_source: Annotated[str, "Where the 5-tier rating came from: label / bare / fallback"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
